# Core Labels for Beta-Trader
# Source of Truth: Notion <-> Linear <-> GitHub Alignment

# --- Automation Group ---
- name: "auto-deploy"
  color: "c5def5"
  description: "Triggered by automated deployment pipelines"
- name: "auto-hook"
  color: "c5def5"
  description: "Related to webhook automation"
- name: "auto-label"
  color: "c5def5"
  description: "Applied by label automation bots"
- name: "auto-monitor"
  color: "c5def5"
  description: "Related to monitoring automation"
- name: "auto-sync"
  color: "c5def5"
  description: "Related to sync automation"
- name: "auto-workflow"
  color: "c5def5"
  description: "Related to GitHub Actions workflows"

# --- Cadence (Priority) Group ---
- name: "p0-blocker"
  color: "b60205"
  description: "Urgent problem blocking development or release"
- name: "p1-high"
  color: "d93f0b"
  description: "High priority, next release included"
- name: "p2-medium"
  color: "fbca04"
  description: "Medium priority, normal scheduling"
- name: "p3-low"
  color: "fef2c0"
  description: "Low priority, nice to have"

# --- Domain Group ---
- name: "domain/ai"
  color: "5319e7"
  description: "AI, ML, and LLM specific components"
- name: "domain/community"
  color: "5319e7"
  description: "Community facing features and docs"
- name: "domain/infrastructure"
  color: "5319e7"
  description: "DevOps, Cloud, and Hardware infra"
- name: "domain/integration"
  color: "5319e7"
  description: "External API and service integrations"
- name: "domain/monitoring"
  color: "5319e7"
  description: "Observability and logging"

# --- Scope (Size) Group ---
- name: "size-xs"
  color: "0e8a16"
  description: "Extra Small size"
- name: "size-s"
  color: "0e8a16"
  description: "Small size"
- name: "size-m"
  color: "0e8a16"
  description: "Medium size"
- name: "size-l"
  color: "0e8a16"
  description: "Large size"
- name: "size-xl"
  color: "0e8a16"
  description: "Extra Large size"
- name: "size-unk"
  color: "d4c5f9"
  description: "Size unknown or TBD"

# --- Special Group ---
- name: "blocked-ext"
  color: "000000"
  description: "Blocked by external dependency"
- name: "blocked-int"
  color: "000000"
  description: "Blocked by internal dependency"
- name: "breaking-change"
  color: "b60205"
  description: "Introduces breaking changes"
- name: "tech-debt"
  color: "a2eeef"
  description: "Technical debt cleanup"

# --- Type Group ---
- name: "bug"
  color: "d73a4a"
  description: "Something isn't working"
- name: "documentation"
  color: "0075ca"
  description: "Improvements or additions to documentation"
- name: "enhancement"
  color: "a2eeef"
  description: "New feature or request"
- name: "feature"
  color: "a2eeef"
  description: "New feature functionality"
- name: "infra"
  color: "c5def5"
  description: "Infrastructure related changes"
- name: "performance"
  color: "ffcfc9"
  description: "Performance Optimization"
- name: "personality"
  color: "d4c5f9"
  description: "Enhancements to AI personality/voice"
- name: "qol-imp"
  color: "c2e0c6"
  description: "Quality of Life improvements"
- name: "refactor"
  color: "ffcfc9"
  description: "Code refactoring without behavior change"
- name: "security"
  color: "aaaaaa"
  description: "Security fixes and improvements"
- name: "social"
  color: "f9d0c4"
  description: "Social features"
- name: "spike"
  color: "f9d0c4"
  description: "Research or investigation task"
